### ISSUE TITLE
Support for setting initial scrolloff value

### ISSUE THREAD

**Issue by acoffman** [tonymajestro/smart-scrolloff.nvim#1]
Hi, love this idea!

In trying it out, I've noticed that scrolloff _only_ gets set when the window is resized. If you do not set a default scrolloff value elsewhere in your config, it will default to zero. It feels a little redundant to have to set it in two places. Would you be interested in a PR that adds an additional autocmd to set up an initial value based on the same calculation?

edit: Thinking about this more, maybe not an additional autocmd but simply just setting the value during `setup`.

**Comment by tonymajestro** [comment]
Thanks for reaching out! I'm unable to reproduce this issue since the WinResized autocmd executes for me on startup. Could you share your plugin configuration with me? Also, could you try adding a print statement to the autocommand to verify that it is being called on startup? I wonder if you have a different plugin that is loading after mine that is overriding the scrolloff value. Also could you double check that you are not overriding this value yourself somewhere in your configuration?

**Comment by tonymajestro** [comment]
I've added a debug branch that you can use to test if the WinResized event is being triggered. Could you try this configuration and let me know if you see the debug print stagements when you open neovim?

```  
  {
    "tonymajestro/smart-scrolloff.nvim",
    branch = "debug",
    opts = {
      scrolloff_percentage = 0.2,
    },
  }

```

**Comment by acoffman** [comment]
Thanks for the followup!

I see some interesting behavior here that I can't quite explain. I am using folke's minimal `init.lua` from [here](https://github.com/folke/lazy.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue) with the block you provided above added.

When I boot `nvim` and type `:messages` I do not see the newly added debug message. Likewise, when I open a file, I do not see the message. `scrolloff` is not set in either case.

Going back to my own "real" config (still using the debug branch you provided) I see the message.... _sometimes_. When I open my `alacritty.toml` for instance, the message does not appear, but when I open my `plugins.lua` file it does. This tells me something in my config is triggering the WinResized event to happen sometimes, but it seems like it does not happen by default in an otherwise minimal setup. At least that's what it is seeming like to me at the moment.

**Comment by tonymajestro** [comment]
That minimal init was very helpful, I was able to reproduce the issue using it. I'm not sure why the WinResized event is triggered inconsistently like that. However I tried your suggestion to initialize the scrolloff during setup and that seems to have fixed it. Could you try the debug branch again and see if you get the correct behavior on startup? If everything looks good then I will update it in the main branch.

**Comment by acoffman** [comment]
I now see the message on startup:

`Initializing scrolloff on startup: 9`


Thanks for the fix!

**Comment by tonymajestro** [comment]
Great thank you! I've updated the main branch so you should be able to use that now. Let me know if you have any issues with it.
